# Generated by Django 4.1.3 on 2022-11-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactionsanswers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reactionsquestion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
